# Generated by Django 4.2.7 on 2025-11-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repuesto',
            options={'ordering': ['nombre'], 'verbose_name': 'Repuesto', 'verbose_name_plural': 'Repuestos'},
        ),
    ]
