# Generated by Django 4.2.7 on 2025-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('ingresos', 'Ingresos de Hoy'), ('pedidos', 'Pedidos Activos'), ('entregas', 'Entregas u Órdenes'), ('inventario', 'Valor de Inventario')], max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('umbral_alerta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Alerta Rápida',
                'verbose_name_plural': 'Alertas Rápidas',
                'ordering': ['tipo'],
            },
        ),
    ]
